# -*- coding: utf-8 -*-
"""SmolLM x Grpo M1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//huggingface.co/prithivMLmods/SmolLM2_135M_Grpo_Gsm8k/blob/main/smollm-grpo/SmolLM%20x%20Grpo%20M1.ipynb
"""

# pip install -q git+https://github.com/huggingface/transformers.git git+https://github.com/huggingface/accelerate.git
# pip install -q datasets huggingface-hub trl
# !pip install -q git+https://github.com/huggingface/peft.git

import sys
sys.path.insert(0, "/home/chandan/test_current/peft/src")

import re
import torch
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import get_peft_model, SOARAConfig
from trl import GRPOConfig, GRPOTrainer

SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

XML_COT_FORMAT = """\
<reasoning>
{reasoning}
</reasoning>
<answer>
{answer}
</answer>
"""

def extract_xml_answer(text: str) -> str:
    answer = text.split("<answer>")[-1]
    answer = answer.split("</answer>")[0]
    return answer.strip()

def extract_hash_answer(text: str) -> str | None:
    if "####" not in text:
        return None
    return text.split("####")[1].strip()

# uncomment middle messages for 1-shot prompting
def get_gsm8k_questions(split = "train") -> Dataset:
    data = load_dataset('openai/gsm8k', 'main')[split] # type: ignore
    data = data.map(lambda x: { # type: ignore
        'prompt': [
            {'role': 'system', 'content': SYSTEM_PROMPT},
            #{'role': 'user', 'content': 'What is the largest single-digit prime number?'},
            #{'role': 'assistant', 'content': XML_COT_FORMAT.format(
            #    reasoning="9 is divisble by 3 and 8 is divisible by 2, but 7 is prime.",
            #    answer="7"
            #)},
            {'role': 'user', 'content': x['question']}
        ],
        'answer': extract_hash_answer(x['answer'])
    }) # type: ignore
    return data # type: ignore

dataset = get_gsm8k_questions()

def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    q = prompts[0][-1]['content']
    extracted_responses = [extract_xml_answer(r) for r in responses]
    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}")
    return [2.0 if r == a else 0.0 for r, a in zip(extracted_responses, answer)]

def int_reward_func(completions, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [extract_xml_answer(r) for r in responses]
    return [0.5 if r.isdigit() else 0.0 for r in extracted_responses]

def strict_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"^<reasoning>\n.*?\n</reasoning>\n<answer>\n.*?\n</answer>\n$"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def soft_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"<reasoning>.*?</reasoning>\s*<answer>.*?</answer>"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def count_xml(text) -> float:
    count = 0.0
    if text.count("<reasoning>\n") == 1:
        count += 0.125
    if text.count("\n</reasoning>\n") == 1:
        count += 0.125
    if text.count("\n<answer>\n") == 1:
        count += 0.125
        count -= len(text.split("\n</answer>\n")[-1])*0.001
    if text.count("\n</answer>") == 1:
        count += 0.125
        count -= (len(text.split("\n</answer>")[-1]) - 1)*0.001
    return count

def xmlcount_reward_func(completions, **kwargs) -> list[float]:
    contents = [completion[0]["content"] for completion in completions]
    return [count_xml(c) for c in contents]

# model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"

model_name = "google/gemma-7b"

if "SmolLM2" in model_name:
    output_dir = "outputs/SmolLM2-135M-GRPO"
    run_name = "SmolLM2-135M-GRPO"
else:
    output_dir="outputs/Qwen-1.5B-GRPO"
    run_name="Qwen-1.5B-GRPO-gsm8k"

training_args = GRPOConfig(
    output_dir=output_dir,
    run_name=run_name,
    learning_rate=5e-6,
    adam_beta1=0.9,
    adam_beta2=0.99,
    weight_decay=0.1,
    warmup_ratio=0.1,
    lr_scheduler_type='cosine',
    logging_steps=1,
    bf16=True,
    per_device_train_batch_size=16,  # Fixed: Must be divisible by num_generations
    gradient_accumulation_steps=4,
    num_generations=16,  # Kept as is
    max_completion_length=786,
    num_train_epochs=1,
    save_steps=100,
    max_grad_norm=0.1,
    report_to="none",
    log_on_each_node=False,
)

soara_config = SOARAConfig(
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "up_proj", "down_proj", "gate_proj"],
    method="v1",
    orthogonality_reg_weight=0,
    soara_dropout=0.0,
    s_dtype_fp32=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map=None
).to("cuda")

model = get_peft_model(model, soara_config)
model.print_trainable_parameters()

from get_chat_template import get_chat_template

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.padding_side = "left"
template_name = "gemma" if "gemma" in model_name.lower() else "chatml"
tokenizer = get_chat_template(tokenizer, chat_template=template_name)

trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    reward_funcs=[
        xmlcount_reward_func,
        soft_format_reward_func,
        strict_format_reward_func,
        int_reward_func,
        correctness_reward_func],
    args=training_args,
    train_dataset=dataset,
)

trainer.train()

# =========================================================================
# Merge SOARA adapter & Evaluate on GSM8K test
# =========================================================================
print("\n" + "=" * 60)
print("TRAINING COMPLETE — merging adapter & evaluating on GSM8K test")
print("=" * 60)

# 1. Merge adapter weights into the base model
model = trainer.model  # may have been wrapped by the trainer
if hasattr(model, "merge_and_unload"):
    model = model.merge_and_unload()
    print("✓ SOARA adapter merged into base model")
elif hasattr(model, "base_model"):
    # Fallback: try accessing through base_model
    if hasattr(model.base_model, "merge_and_unload"):
        model = model.base_model.merge_and_unload()
        print("✓ SOARA adapter merged (via base_model)")
    else:
        print("⚠ merge_and_unload not found — evaluating with adapter attached")
else:
    print("⚠ No PEFT wrapper detected — evaluating model as-is")

model.eval()

# Optionally save the merged model
merged_dir = output_dir + "/merged"
model.save_pretrained(merged_dir)
tokenizer.save_pretrained(merged_dir)
print(f"✓ Merged model saved to {merged_dir}")

# 2. Load GSM8K test split
test_data = load_dataset("openai/gsm8k", "main")["test"]
print(f"✓ Loaded {len(test_data)} GSM8K test samples")

# 3. Evaluation helpers
def extract_xml_answer_eval(text: str) -> str:
    """Extract from <answer>...</answer> tags (matches training format)."""
    if "<answer>" in text and "</answer>" in text:
        ans = text.split("<answer>")[-1].split("</answer>")[0].strip()
        return ans
    return ""

def extract_number(text: str):
    """Fallback: pull the last number from a string."""
    nums = re.findall(r"[+-]?\d+(?:,\d{3})*(?:\.\d+)?", text)
    if nums:
        return nums[-1].replace(",", "")
    return None

def normalize_numeric(val: str) -> str:
    """Normalize to a comparable numeric string."""
    try:
        return str(int(float(val.replace(",", ""))))
    except (ValueError, OverflowError):
        return val.strip()

# 4. Run evaluation
correct = 0
total = 0
method_stats = {"xml": 0, "number_fallback": 0, "none": 0}

eval_batch_size = 32
device = next(model.parameters()).device

print(f"\nEvaluating (batch_size={eval_batch_size}) …")
for start_idx in range(0, len(test_data), eval_batch_size):
    end_idx = min(start_idx + eval_batch_size, len(test_data))
    batch_questions = [test_data[i]["question"] for i in range(start_idx, end_idx)]
    batch_gt_raw = [test_data[i]["answer"] for i in range(start_idx, end_idx)]
    batch_gt = [extract_hash_answer(a) for a in batch_gt_raw]

    # Tokenize all prompts
    all_input_ids = []
    for question in batch_questions:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": question},
        ]
        ids = tokenizer.apply_chat_template(
            messages, tokenize=True, add_generation_prompt=True
        )
        all_input_ids.append(ids)

    # Left-pad to the longest prompt
    max_len = max(len(ids) for ids in all_input_ids)
    padded_ids = []
    attention_masks = []
    for ids in all_input_ids:
        pad_len = max_len - len(ids)
        padded_ids.append([tokenizer.pad_token_id] * pad_len + ids)
        attention_masks.append([0] * pad_len + [1] * len(ids))

    input_ids = torch.tensor(padded_ids, dtype=torch.long, device=device)
    attention_mask = torch.tensor(attention_masks, dtype=torch.long, device=device)

    with torch.no_grad():
        gen_ids = model.generate(
            input_ids,
            attention_mask=attention_mask,
            max_new_tokens=786,
            do_sample=False,
            temperature=None,
            top_p=None,
        )

    # Decode and evaluate each sample
    for j in range(len(batch_questions)):
        gen_start = max_len
        gen_text = tokenizer.decode(gen_ids[j][gen_start:], skip_special_tokens=True)

        pred_ans = extract_xml_answer_eval(gen_text)
        if pred_ans:
            method = "xml"
        else:
            pred_ans = extract_number(gen_text) or ""
            method = "number_fallback" if pred_ans else "none"
        method_stats[method] += 1

        pred_norm = normalize_numeric(pred_ans) if pred_ans else "NONE"
        gt_norm = normalize_numeric(batch_gt[j]) if batch_gt[j] else "NONE"
        is_correct = pred_norm == gt_norm
        correct += int(is_correct)
        total += 1

        status = "✓" if is_correct else "✗"
        if total <= 5 or total % 50 == 0 or not is_correct:
            print(f"  [{total}] {status}  GT={gt_norm}  Pred={pred_norm} ({method})")

    acc = correct / total * 100
    print(f"  ... {total}/{len(test_data)} done — accuracy: {acc:.2f}%")

# 5. Final report
final_acc = correct / total if total > 0 else 0.0
print(f"\n\n{'=' * 60}")
print(f"GSM8K TEST RESULTS")
print(f"{'=' * 60}")
print(f"  Model:    {model_name}")
print(f"  Correct:  {correct} / {total}")
print(f"  Accuracy: {final_acc:.4f}  ({final_acc * 100:.2f}%)")
print(f"\n  Extraction methods:")
for m, c in method_stats.items():
    pct = c / total * 100 if total > 0 else 0
    print(f"    {m:20s}: {c:5d}  ({pct:.1f}%)")
print("=" * 60)